### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Rmano** [maxerbox/Planet-Lander-with-pygame#2]
Hi, thanks for the nice game! 

I would like to know which kind of licensing this game has. I'd like to use parts of it to learn PyGame and at the same time adding different physics to the simulation (variable mass, wind, atmosphere). The game you say it is based on (albeit very lightly, it seems to me) is released under a MIT license.

Thanks!

**Comment by maxerbox** [comment]
> 
> 
> Hi, thanks for the nice game!
> 
> I would like to know which kind of licensing this game has. I'd like to use parts of it to learn PyGame and at the same time adding different physics to the simulation (variable mass, wind, atmosphere). The game you say it is based on (albeit very lightly, it seems to me) is released under a MIT license.
> 
> Thanks!

I need to ask the other creator if he is okay to release the code under MIT.
I'm pretty sure he is ok with it

**Comment by Rmano** [comment]
Thanks!
